### ISSUE TITLE
ORA-12514: TNS:listener does not currently know of service requested in connect descriptorOracle 

### ISSUE THREAD

**Issue by Geoneer** [Geoneer/KPN-Webservice#10]
ORA-12514: TNS:listener does not currently know of service requested in connect descriptorOracle

**Comment by Geoneer** [comment]
Oracle Data Provider for .NET   at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at sql.sql_execute(String i) in e:\Webs\geoexplorer_webservice\App_Code\sql.cs:line 253
