### ISSUE TITLE
 Access to the path &#39;E:\Webs\geoexplorer_webservice\App_Data\errors.log&#39; is denied.

### ISSUE THREAD

**Issue by Geoneer** [Geoneer/KPN-Webservice#7]
System.UnauthorizedAccessException: Access to the path &#39;E:\Webs\geoexplorer_webservice\App_Data\errors.log&#39; is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at logger.StreamWriterDataFile(Exception i) in e:\Webs\geoexplorer_webservice\App_Code\logger.cs:line 8
   at sql.import(String DataInput, String style, String tblname, String user, String geomTable, String geomTableField, String titel, String dataTableField) in e:\Webs\geoexplorer_webservice\App_Code\sql.cs:line 75

**Comment by Geoneer** [comment]
![image](https://cloud.githubusercontent.com/assets/218929/8303830/1ef6c2fe-19a1-11e5-98db-c22fc4f6449c.png)

**Comment by Geoneer** [comment]
https://www.bluevalleytech.com/techtalk/blog/assigning-ntfs-folder-permission-to-iis7-application-pools.aspx

![image](https://cloud.githubusercontent.com/assets/218929/8303995/77c3f568-19a2-11e5-948b-fc612fe5579d.png)

**Comment by Geoneer** [comment]
App_Data mapje verwijderd en weer toegevoegd. Files worden weer aangemaakt.
